# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "functions-template"
client_id = "8b8503339485f01e34ab0d7ca2c775de"
application_url = "https://english-taylor-lambda-naples.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://english-taylor-lambda-naples.trycloudflare.com/auth/callback",
  "https://english-taylor-lambda-naples.trycloudflare.com/auth/shopify/callback",
  "https://english-taylor-lambda-naples.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "inmers.myshopify.com"
